# Paradise Web Services

Hostname: '127.0.0.1'

# Port Settings
WebServicePort: 8080
FileServerPort: 8081
TCPCommPort: 8082

# Database Settings
DatabaseServer: ''
DatabasePort: 3306 # MySQL/MariaDB
DatabaseUser: ''
DatabasePassword: ''
DatabaseName: ''

#region Web Service Settings
WebServicePrefix: 'UberStrike.DataCenter.WebService.CWS.'
WebServiceSuffix: 'Contract.svc'
EncryptionInitVector: 'aaaaBBBBccccDDDD' # Must be 16 characters
EncryptionPassPhrase: 'mysupersecretpassphrase'
ServerPassPhrases:
  - Id: '00000000-0000-0000-0000-000000000000'
    PassPhrase: 'mysupersecretpassphrase'
PluginBlacklist:
  - MyBlacklistedPlugin.plugin